
CREATE TABLE IF NOT EXISTS PROJECT (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  description VARCHAR(250)
);

CREATE TABLE IF NOT EXISTS TASK (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(250) NOT NULL,
  description VARCHAR(250),
  status ENUM('TO_DO', 'IN_PRORESS', 'DONE') NOT NULL,
  due_date DATETIME,
  FOREIGN KEY (project_id) REFERENCES PROJECT(id)
);